---

- name: collect device information
  register: nxosfacts_out
  nxos_facts:
    gather_subset: all
  tags:
  - getfacts

#- name: collect sh version information
#  register: shver_out
#  nxos_command:
#    commands: show version
#  tags:
#  - info
#
  
