---

- name: collect device information
  register: nxosfacts_out
  nxos_facts:
    gather_subset: all
  tags:
  - info

- name: collect sh version information
  register: shver_out
  nxos_command:
    commands: show version
  tags:
  - info

- debug:
    msg: system serial is {{(shver_out | to_nice_json).stdout.0.TABLE_package_list.ROW_package_list | map(attribute='proc_board_id')}}
  tags:
  - info

- name: write all the results to JSON file
  copy:
    content: "{{ nxosfacts_out | to_nice_json }}"
    dest: "{{output_folder}}/json/{{inventory_hostname}}_nxosfacts.json"
  tags:
  - info