---

- name: collect device information
  register: nxosfacts_out
  nxos_facts:
    gather_subset: all
  tags:
  - info

- name: collect sh version information
  register: shver_out
  nxos_command:
    commands: show version | json
  tags:
  - info

- debug:
    msg: system serial is: {{shver_out.proc_board_id}}

- name: write all the results to JSON file
  copy:
    content: "{{ nxosfacts_out | to_nice_json }}"
    dest: "{{output_folder}}/json/{{inventory_hostname}}_nxosfacts.json"
  tags:
  - info