---

- name: collect device information
  register: iosfacts_out
  ios_facts:
    gather_subset: all

- name: output to file
  become: yes
  become_method: su
  become_user: netadmin
  copy:
    content: "{{ iosfacts_out | to_nice_json }}"
    dest: "/etc/ansible/output/{{inventory_hostname}}_iosfacts.json"

- name: run show version on remote devices
  become: yes
  ios_command:
    commands: 
      - command: show version
  register: result

- name: print "show version" command ouput
  debug:
    var: result.stdout

- name: output to file
  become: yes
  become_method: su
  become_user: netadmin
  copy: 
    content: "{% for host in ansible_play_hosts %}From host: {{ host }}\n{{ result.stdout_lines | to_nice_json }}\n{% endfor %}"
    dest: ../output/tasks_out.json
  delegate_to: localhost
  run_once: True
