---

- name: write overlay config file
  template:
    src: overlay_services_conf.j2
    dest: "{{ output_folder }}/config/{{ inventory_hostname }}_overlay_services.conf"
  tags:
  - config
  - overlay