---

#copy to ftp server    
- name: tftp file copy
  hosts: tftp-server
  tasks:
  - name: deleting config folder
    file: 
      path: '{{tftp_folder}}/config'
      state: absent
    run_once: true
    tags:
      - tftp_upload_reset
  - name: creating config folder
    file: 
      path: '{{tftp_folder}}/config'
      state: directory
      mode: 0777
    run_once: true
    tags:
     - tftp_upload_reset
  - name: Copying complete configurations to tftp home
    copy:
      src: "{{output_folder}}/config/{{hostvars[item].inventory_hostname}}_complete.conf"
      dest: "{{tftp_folder}}/conf.{{hostvars[item].serial_num}}"
#      owner: root
#      group: root
#      mode: '0777'
    loop: "{{ query('inventory_hostnames', 'nexus_switch') }}"
    tags:
    - tftp_upload