---
  
- name: output folder reset
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - name: deleting output folder
    file: 
      path: '{{output_folder}}/'
      state: absent
    run_once: true
    tags:
      - config
      - info
  - name: creating output folder
    file: 
      owner: netadmin
      path: '{{output_folder}}/'
      state: directory
      mode: 0777
    run_once: true
    tags:
      - config
      - info

  - name: creating config folder
    file: 
      owner: netadmin
      path: '{{output_folder}}/config'
      state: directory
      mode: 0777
    run_once: true
    tags:
      - config
      - info

- name: create leaf device config files
  gather_facts: no
  hosts: leaf
  vars_files: ../inventory/vars/services.yml
  roles:
    - switch-leaf

- name: create spine device config files
  gather_facts: no
  hosts: spine
  vars_files: ../inventory/vars/services.yml
  roles:
    - switch-spine