---

# First block of tasks: cleaning up the config and tftp folder
- name: output folder reset
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - name: deleting config folder
    file: 
      path: '{{output_folder}}/config'
      state: absent
    run_once: true
    tags:
      - config
  - name: creating config folder
    file: 
#      owner: netadmin
      path: '{{output_folder}}/config'
      state: directory
      mode: 0777
    run_once: true
    tags:
    - config

# Second block of tasks: creating device config files
- name: create basic device config files
  connection: local
  gather_facts: no
  hosts: nexus_switch
#  vars_files: ../inventory/vars/services.yml
  roles:
  - fabric
      
- name: create leaf device config files
  connection: local
  gather_facts: no
  hosts: leaf
#  vars_files: ../inventory/vars/services.yml
  roles:
  - switch-leaf
  
- name: create border leaf device config files
  connection: local
  gather_facts: no
  hosts: border-leaf
#  vars_files: ../inventory/vars/services.yml
  roles:
  - switch-border-leaf

- name: create spine device config files
  connection: local
  gather_facts: no
  hosts: spine
#  vars_files: ../inventory/vars/services.yml
  roles:
  - switch-spine

# Third block of tasks: merging all specific config files into one
- name: create config files
  connection: local
  gather_facts: no
  hosts: nexus_switch
  tasks:
  - name: Assembling basic configurations
    assemble:
     src: "{{output_folder}}/config"
     regexp: '{{inventory_hostname}}_1_'
     dest: "{{output_folder}}/config/{{inventory_hostname}}_basic.conf"
    tags:
    - config
    - basic
  - name: Assembling underlay configurations
    assemble:
     src: "{{output_folder}}/config"
     regexp: '{{inventory_hostname}}_2_'
     dest: "{{output_folder}}/config/{{inventory_hostname}}_underlay.conf"
    tags:
    - config
    - underlay
  - name: Assembling overlay configurations
    assemble:
     src: "{{output_folder}}/config"
     regexp: '{{inventory_hostname}}_3_'
     dest: "{{output_folder}}/config/{{inventory_hostname}}_overlay.conf"
    tags:
    - config
    - overlay
  - name: Assembling services configurations
    assemble:
     src: "{{output_folder}}/config"
     regexp: '{{inventory_hostname}}_4_'
     dest: "{{output_folder}}/config/{{inventory_hostname}}_services.conf"
    tags:
    - config
    - services
  - name: Assembling complete configurations
    assemble:
     src: "{{output_folder}}/config"
     regexp: '{{inventory_hostname}}_\d_'
     dest: "{{output_folder}}/config/{{inventory_hostname}}_complete.conf"
    tags:
    - config
    - complete

#copy to ftp server    
- name: tftp file copy
  hosts: tftp-server
  tasks:
  - name: deleting config folder
    file: 
      path: '{{tftp_folder}}/config'
      state: absent
    run_once: true
    tags:
      - tftp_upload
  - name: creating config folder
    file: 
      path: '{{tftp_folder}}/config'
      state: directory
      mode: 0777
    run_once: true
    tags:
     - tftp_upload
  - name: Copying complete configurations to tftp home
    copy:
      src: "{{output_folder}}/config/{{hostvars[item].inventory_hostname}}_complete.conf"
      dest: "{{tftp_folder}}/config/{{hostvars[item].serial_num}}.conf"
#      owner: root
#      group: root
#      mode: '0777'
    loop: "{{ query('inventory_hostnames', 'nexus_switch') }}"
    tags:
    - tftp_upload