---

- name: configure key based authentication on leaf switches
  gather_facts: no
  hosts: nexus-switch


  tasks:
   - name: copy key file
     cli_command:
      command: copy scp://{{user}}@172.16.1.1/home/{{user}}/.ssh/{{user}}_id_rsa.pub bootflash:/ vrf management
      check_all: True
      prompt:
       - "connecting"
       - "overwrite"
       - "password: "
      answer: 
       - "yes"
       - 'y'
       - "{{password}}"
     register: command_output

#   - name: PRINT TO TERMINAL WINDOW
#     debug:
#      msg: "{{command_output.stdout}}"
      
   - name: create user
     nxos_config:
      lines:
       - username {{user}} role network-admin
       - username {{user}} sshkey file bootflash:{{user}}_id_rsa.pub
      replace: line
