---

- name: Enable feature scp-server
  nxos_feature:
    feature: scp-server
    state: enabled
  tags:
  - first_deploy
#- name: Copying user's RSA key file into devices 
#  nxos_file_copy:
#    local_file: "{{key_path}}/{{id}}_id_rsa.pub"
#    remote_file: "{{id}}_id_rsa.pub"
#  tags:
#  - key_access
- name: create user
  nxos_config:
    lines: 
     - "username {{id}} password {{id_pass}}  role network-admin"
  notify: save_config
  tags:
  - first_deploy
#- name: enable key auth for machine user
#  nxos_config:
#    lines: 
#     - "username {{id}} sshkey file bootflash:{{id}}_id_rsa.pub"
#  notify: save_config
#  tags:
#  - key_access
#only for lab purposes
- name: Enable temporary license on devices
  nxos_config:
    lines: license grace-period
  notify: save_config
  tags:
  - lab

