---
  
- name: output folder reset
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
  - name: deleting output folder
    file: 
      path: '{{output_folder}}/'
      state: absent
    run_once: true

  - name: creating output folder
    file: 
      owner: netadmin
      path: '{{output_folder}}/'
      state: directory
      mode: 0777
    run_once: true

  - name: creating web folder
    file: 
      owner: netadmin
      path: '{{output_folder}}/web'
      state: directory
      mode: 0777
    run_once: true

  - name: creating json folder
    file: 
      owner: netadmin
      path: '{{output_folder}}/json'
      state: directory
      mode: 0777
    run_once: true

  - name: creating CSS folder
    file: 
      owner: netadmin
      path: '{{output_folder}}/web/css'
      state: directory
      mode: 0777
    run_once: true

  - name: copy CSS into web folder
    copy:
      src: "/home/netadmin/css/"
      dest: "{{output_folder}}/web/css/"
      directory_mode: yes

- name: gathering complete spine device info collection
  gather_facts: no
  hosts: spine

  roles:
    - switch-spine

- name: gathering complete leaf device info collection
  gather_facts: no
  hosts: leaf

  roles:
    - switch-leaf
