---
# The first Play gets the timestamp from the Ansible server and stores it into 'timestamp' variable
- name: Get timestamp
  gather_facts: yes
  hosts: localhost
  tasks:
  - set_fact:
      timestamp: "{{ ansible_date_time.iso8601 }}"
    tags:
    - simple_config
    
# The second Play gets system serial and saves the device's runnin-config files into '{{ output_folder }}/backup' folder
- name: Config backup
  gather_facts: no
  hosts: nexus_switch
  tasks:
  # Gathering info about system
  - name: Running 'show version' on remote devices
    nxos_command:
      commands: 
        - command: show version
          output: json
    register: nxos_version
    tags:
    - serial_check
  # The task fails if inventory serial and device serial mismatch
  - name: verifying Serial Number
    fail:
      msg: "ERROR: serial number mismatch, device serial number is {{nxos_version.stdout.0.proc_board_id}}, inventory serial number is {{serial_num}}, stopping execution."
    # Errors triggered on serial mismatch
    when: nxos_version.stdout.0.proc_board_id != serial_num   
    tags:
    - serial_check
  - name: config checkpoint for rollback
    nxos_rollback:
     checkpoint_file: backup.cfg
    tags:
    - simple_config
    

    
# The fourth Play deploys the simple config into the devices
- name: Config Deploy
  gather_facts: no
  hosts: nexus_switch 
  tasks: 
  # Deploy config through nxos_commands fails if there is any syntax error, this kind of deployment highlights any templating issue!
  - name: disable interactive terminal
    nxos_command:
     commands: 
       - command: terminal dont-ask
    tags:
    - simple_config
     
  - block:
    - name: deploy command
      vars:
       ansible_command_timeout: 40
      nxos_config:
       lines:
        - "{{simple_command}}"
      notify: save_config
    #if deploy fails then roll back to the last backup
    rescue:
     - name: Include rescue tasks
       include_tasks: rescue.yml
    tags:
    - simple_config
   
  handlers:
  - name: save_config
    nxos_config:
      save_when: modified
    tags:
    - simple_config_save
